"""empty message

Revision ID: 2de775ec19f8
Revises: 22dc2fba08e2
Create Date: 2019-11-28 17:38:33.708213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2de775ec19f8'
down_revision = '22dc2fba08e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercise', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'exercise', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'exercise', type_='foreignkey')
    op.drop_column('exercise', 'user_id')
    # ### end Alembic commands ###
